### PR TITLE
Update Appendix-A.md

### PR DESCRIPTION
**Pull request by oliviercp**
:)

### CODE REVIEW

**Comment by RashidGilanpour** [comment]
Hey Man sorry this change sucks! NOPE

**Comment by ocompagne** [comment]
Thanks for considering...

**Comment by ocompagne** [comment]
Re-open

**Comment by ocompagne** [comment]
Come on dude!

**Comment by RashidGilanpour** [comment]
never!

**Comment by ocompagne** [comment]
What do you see now?

**Pull request closed without merging**
